FROM johnnycubides/linux-litex-base:base

WORKDIR /opt/

RUN git clone https://github.com/riscv/riscv-gnu-toolchain && \
      cd riscv-gnu-toolchain && \
      git submodule update --init --recursive
# construyendo...
RUN cd riscv-gnu-toolchain && \
      ./configure --prefix=/opt/riscv --with-arch=rv32gc --with-abi=ilp32d
# instalando 
RUN cd riscv-gnu-toolchain && \
      make linux

RUN echo "finished compilation of riscv tool chain"
