FROM johnnycubides/linux-litex-base:base

RUN wget https://github.com/seccomp/libseccomp/releases/download/v2.4.1/libseccomp-2.4.1.tar.gz && \
      tar xvf libseccomp-2.4.1.tar.gz && \
      rm libseccomp-2.4.1.tar.gz && \
      cd libseccomp-2.4.1 && \
      ./configure && \
      make [V=0] && \
      make install

RUN git clone https://github.com/YosysHQ/nextpnr nextpnr && \
       cd nextpnr && \
       cmake -DARCH=ice40 -DBUILD_GUI=OFF -DCMAKE_INSTALL_PREFIX=/usr/local . && \
       make -j$(nproc) && \
       make install
